import Head from "next/head";
import React, { useState, useEffect, createRef } from "react";
import HomeSection from "../src/sections/Home";
import AboutSection from "../src/sections/About";
import ContactSection from "../src/sections/Contact";
import PortfolioSection from "../src/sections/Portfolio";
import { useScreen } from "../src/context/ScreenContext";

export default function Home() {
  const [sectionRefs, setSectionRefs] = useState([]);
  const screenContext = useScreen();
  const { currentSection, windowYOffset, screenHeight, setSectionIndicator } =
    screenContext;

  useEffect(() => {
    setSectionRefs((sectionRefs) =>
      Array(4)
        .fill()
        .map((_, i) => sectionRefs[i] || createRef())
    );
  }, []);

  useEffect(() => {
    scrollToSection(currentSection);
  }, [currentSection]);

  useEffect(() => {
    evaluateSection();
  }, [windowYOffset]);

  const scrollToSection = (num) => {
    if (sectionRefs[num] && sectionRefs[num].current) {
      sectionRefs[num].current.scrollIntoView({ behavior: "smooth" });
    }
  };

  const evaluateSection = () => {
    const focused = sectionRefs.filter(
      (ref) =>
        ref.current &&
        ref.current.getBoundingClientRect().top > 0 - 10 &&
        ref.current.getBoundingClientRect().top < screenHeight + 10
    )[0];

    // if (
    //   sectionRefs.length > 1 &&
    //   sectionRefs[0] &&
    //   sectionRefs[0].current &&
    //   sectionRefs[1] &&
    //   sectionRefs[1].current &&
    //   sectionRefs[2] &&
    //   sectionRefs[2].current &&
    //   sectionRefs[3] &&
    //   sectionRefs[3].current
    // ) {
    //   console.log(
    //     `home: ${sectionRefs[0].current.getBoundingClientRect().top}`
    //   );
    //   console.log(
    //     `home: ${sectionRefs[0].current.getBoundingClientRect().bottom}`
    //   );
    //   console.log(
    //     `about: ${sectionRefs[1].current.getBoundingClientRect().top}`
    //   );
    //   console.log(
    //     `home: ${sectionRefs[1].current.getBoundingClientRect().bottom}`
    //   );
    //   console.log(
    //     `portfolio: ${sectionRefs[2].current.getBoundingClientRect().top}`
    //   );
    //   console.log(
    //     `contact: ${sectionRefs[3].current.getBoundingClientRect().top}`
    //   );
    //   console.log(`screen height: ${screenHeight + 20}`);
    //   console.log("=====================================");
    // }

    if (focused !== null && focused?.current !== undefined) {
      const focusedSection = focused.current.id.replace(/section__/, "");
      setSectionIndicator(+focusedSection);
    }

    if (windowYOffset === 0) return setSectionIndicator(0);
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeSection sRef={sectionRefs[0]} />
      <AboutSection sRef={sectionRefs[1]} />
      <PortfolioSection sRef={sectionRefs[2]} />
      <ContactSection sRef={sectionRefs[3]} />
    </div>
  );
}
